import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >

      <body className="min-h-full flex flex-col font-sans">
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(){
                function clean(){var e=document.querySelectorAll('svg');for(var i=0;i<e.length;i++){var s=e[i];for(var j=s.attributes.length-1;j>=0;j--){var a=s.attributes[j];if(a.name.indexOf('data-darkreader-')===0)s.removeAttribute(a.name)}if(s.style){for(var k=s.style.length-1;k>=0;k--){var p=s.style[k];if(p.indexOf('--darkreader-')===0)s.style.removeProperty(p)}}}}
                clean();var t=setInterval(clean,50);setTimeout(function(){clearInterval(t)},8e3)
              })();
            `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
